//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NATAutoMapper.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NatAutoMapper {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NatAutoMapper() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NATAutoMapper.Properties.NatAutoMapper", typeof(NatAutoMapper).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Regola già esistente..
        /// </summary>
        public static string AlreadyExistingError {
            get {
                return ResourceManager.GetString("AlreadyExistingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il servizio indicato non esiste..
        /// </summary>
        public static string ArgumentExceptionKnownServiceInexistentText {
            get {
                return ResourceManager.GetString("ArgumentExceptionKnownServiceInexistentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La porta privata o la porta pubblica fornite non sono valide..
        /// </summary>
        public static string ArgumentExceptionKnownServiceInvalidPort {
            get {
                return ResourceManager.GetString("ArgumentExceptionKnownServiceInvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il nome del servizio non può essere nullo o una stringa vuota..
        /// </summary>
        public static string ArgumentNullExceptionKnownServiceNameText {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionKnownServiceNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a L&apos;indirizzo IP non può essere nullo..
        /// </summary>
        public static string ArgumentNullExceptionKnownServiceNullAddressText {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionKnownServiceNullAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confermare eliminazione (S/N)? .
        /// </summary>
        public static string ClosePortConfirmation {
            get {
                return ResourceManager.GetString("ClosePortConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;eliminazione delle regole, codice di errore .
        /// </summary>
        public static string ClosePortError {
            get {
                return ResourceManager.GetString("ClosePortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non è stata scelta nessuna opzione oppure l&apos;opzione scelta non è valida, nessuna operazione eseguita..
        /// </summary>
        public static string ClosePortNoOptionSelected {
            get {
                return ResourceManager.GetString("ClosePortNoOptionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non è stata trovata nessun&apos;altra regola con la descrizione fornita..
        /// </summary>
        public static string ClosePortNoOtherRuleFound {
            get {
                return ResourceManager.GetString("ClosePortNoOtherRuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non è stata trovata nessuna regola con la descrizione fornita..
        /// </summary>
        public static string ClosePortNoRuleFound {
            get {
                return ResourceManager.GetString("ClosePortNoRuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Regola eliminata..
        /// </summary>
        public static string ClosePortRuleDeleted {
            get {
                return ResourceManager.GetString("ClosePortRuleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Descrizione della regola da eliminare: .
        /// </summary>
        public static string ClosePortRuleDescription {
            get {
                return ResourceManager.GetString("ClosePortRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante la creazione della regola..
        /// </summary>
        public static string CreationError {
            get {
                return ResourceManager.GetString("CreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni correnti del programma.
        /// </summary>
        public static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;eliminazione della regola..
        /// </summary>
        public static string DeletionError {
            get {
                return ResourceManager.GetString("DeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricerca dispositivi NAT con supporto UPnP....
        /// </summary>
        public static string DeviceDiscovery {
            get {
                return ResourceManager.GetString("DeviceDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trovato 1 dispositivo..
        /// </summary>
        public static string DeviceFound {
            get {
                return ResourceManager.GetString("DeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trovati .
        /// </summary>
        public static string DevicesFound1 {
            get {
                return ResourceManager.GetString("DevicesFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  dispositivi..
        /// </summary>
        public static string DevicesFound2 {
            get {
                return ResourceManager.GetString("DevicesFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il percorso indicato non si riferisce a nessuna directory esistente..
        /// </summary>
        public static string DirectoryNotFoundExceptionText {
            get {
                return ResourceManager.GetString("DirectoryNotFoundExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire tempo di ricerca dispositivi (lasciare vuoto o 0 per default): .
        /// </summary>
        public static string DiscoveryTimeSettingEdit {
            get {
                return ResourceManager.GetString("DiscoveryTimeSettingEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;enumerazione delle regole di port mapping..
        /// </summary>
        public static string EnumerationError {
            get {
                return ResourceManager.GetString("EnumerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;enumerazione delle regole, codice di errore .
        /// </summary>
        public static string EnumerationErrorDetailedText {
            get {
                return ResourceManager.GetString("EnumerationErrorDetailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File non trovato..
        /// </summary>
        public static string FileNotFoundExceptionText {
            get {
                return ResourceManager.GetString("FileNotFoundExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; stato selezionato il primo dispositivo trovato..
        /// </summary>
        public static string FirstDeviceFoundSelected {
            get {
                return ResourceManager.GetString("FirstDeviceFoundSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scelta del primo dispositivo trovato disattivata..
        /// </summary>
        public static string FirstDeviceSelectionSettingDisabled {
            get {
                return ResourceManager.GetString("FirstDeviceSelectionSettingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scelta del primo dispositivo trovato attivata..
        /// </summary>
        public static string FirstDeviceSelectionSettingEnabled {
            get {
                return ResourceManager.GetString("FirstDeviceSelectionSettingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parametri forniti insufficienti..
        /// </summary>
        public static string InsufficientArgumentsError {
            get {
                return ResourceManager.GetString("InsufficientArgumentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rilevati parametri non validi..
        /// </summary>
        public static string InvalidArgumentsError {
            get {
                return ResourceManager.GetString("InvalidArgumentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona non valida, selezionare un&apos;altro dispositivo: .
        /// </summary>
        public static string InvalidDeviceSelection {
            get {
                return ResourceManager.GetString("InvalidDeviceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tempo di validità non valido..
        /// </summary>
        public static string InvalidLifetimeError {
            get {
                return ResourceManager.GetString("InvalidLifetimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezione non valida..
        /// </summary>
        public static string InvalidOperationSelection {
            get {
                return ResourceManager.GetString("InvalidOperationSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Porta privata non valida..
        /// </summary>
        public static string InvalidPrivatePortError {
            get {
                return ResourceManager.GetString("InvalidPrivatePortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Protocollo non valido..
        /// </summary>
        public static string InvalidProtocolError {
            get {
                return ResourceManager.GetString("InvalidProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Porta pubblica non valida..
        /// </summary>
        public static string InvalidPublicPortError {
            get {
                return ResourceManager.GetString("InvalidPublicPortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Script non valido..
        /// </summary>
        public static string InvalidScript {
            get {
                return ResourceManager.GetString("InvalidScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore I/O: .
        /// </summary>
        public static string IOExceptionDetailedText {
            get {
                return ResourceManager.GetString("IOExceptionDetailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 0) Esci dal programma.
        /// </summary>
        public static string MainMenuCommand0 {
            get {
                return ResourceManager.GetString("MainMenuCommand0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1) Visualizza attuale mappatura porte.
        /// </summary>
        public static string MainMenuCommand1 {
            get {
                return ResourceManager.GetString("MainMenuCommand1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 2) Apri porta.
        /// </summary>
        public static string MainMenuCommand2 {
            get {
                return ResourceManager.GetString("MainMenuCommand2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 3) Apri porta (regole predefinita).
        /// </summary>
        public static string MainMenuCommand3 {
            get {
                return ResourceManager.GetString("MainMenuCommand3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 4) Chiudi porta.
        /// </summary>
        public static string MainMenuCommand4 {
            get {
                return ResourceManager.GetString("MainMenuCommand4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 5) Pulisci finestra.
        /// </summary>
        public static string MainMenuCommand5 {
            get {
                return ResourceManager.GetString("MainMenuCommand5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 6) Cambia impostazioni.
        /// </summary>
        public static string MainMenuCommand6 {
            get {
                return ResourceManager.GetString("MainMenuCommand6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare l&apos;operazione da eseguire:.
        /// </summary>
        public static string MainMenuSelection {
            get {
                return ResourceManager.GetString("MainMenuSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;enumerazione delle interfacce di rete: .
        /// </summary>
        public static string NetworkInformationExceptionDetailedText1 {
            get {
                return ResourceManager.GetString("NetworkInformationExceptionDetailedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a , codice di errore nativo: .
        /// </summary>
        public static string NetworkInformationExceptionDetailedText2 {
            get {
                return ResourceManager.GetString("NetworkInformationExceptionDetailedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante il recupero dell&apos;indirizzo IP locale..
        /// </summary>
        public static string NetworkInformationExceptionText {
            get {
                return ResourceManager.GetString("NetworkInformationExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun dispositivo trovato..
        /// </summary>
        public static string NoDeviceFound {
            get {
                return ResourceManager.GetString("NoDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non sono stati forniti i parametri necessari oppure non sono validi..
        /// </summary>
        public static string NoneOrInvalidParameters {
            get {
                return ResourceManager.GetString("NoneOrInvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessuna operazione selezionata, nessuna modifica effettuata..
        /// </summary>
        public static string NoOperationSelected {
            get {
                return ResourceManager.GetString("NoOperationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun&apos;altra regola trovata..
        /// </summary>
        public static string NoOtherRuleFound {
            get {
                return ResourceManager.GetString("NoOtherRuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessuna regola di port mapping impostata..
        /// </summary>
        public static string NoPortMappingFound {
            get {
                return ResourceManager.GetString("NoPortMappingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun regola trovata..
        /// </summary>
        public static string NoRuleFound {
            get {
                return ResourceManager.GetString("NoRuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a L&apos;indirizzo IP non è un indirizzo locale, non è in un formato corretto oppure c&apos;è stato un errore nel recuperare l&apos;indirizzo locale..
        /// </summary>
        public static string NotLocalIPError {
            get {
                return ResourceManager.GetString("NotLocalIPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Si possono soltanto indicare indirizzi IP locali..
        /// </summary>
        public static string NotLocalIPErrorOpenPort {
            get {
                return ResourceManager.GetString("NotLocalIPErrorOpenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operazione non supportata: .
        /// </summary>
        public static string NotSupportedExceptionDetailedText {
            get {
                return ResourceManager.GetString("NotSupportedExceptionDetailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Risponsta non valida..
        /// </summary>
        public static string OpenKnownPortInvalidResponse {
            get {
                return ResourceManager.GetString("OpenKnownPortInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire un filtro per l&apos;enumerazione delle regole note, il filtro può essere un protocollo (TCP o UDP), un numero di porta oppure una parola: .
        /// </summary>
        public static string OpenKnownPortListingFilter {
            get {
                return ResourceManager.GetString("OpenKnownPortListingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lista filtrata regole note (in gruppi di 10, premere Invio per continuare, Esc per terminare, r per reinserire il filtro):.
        /// </summary>
        public static string OpenKnownPortListingFiltered {
            get {
                return ResourceManager.GetString("OpenKnownPortListingFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessuna regola trovata..
        /// </summary>
        public static string OpenKnownPortListingFilteredNoRule {
            get {
                return ResourceManager.GetString("OpenKnownPortListingFilteredNoRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lista completa regole note (in gruppi di 10, premere Invio per continuare, Esc per terminare, r per inserire un filtro):.
        /// </summary>
        public static string OpenKnownPortListingNoFilter {
            get {
                return ResourceManager.GetString("OpenKnownPortListingNoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessuna regola selezionata..
        /// </summary>
        public static string OpenKnownPortNoRuleSelected {
            get {
                return ResourceManager.GetString("OpenKnownPortNoRuleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire il numero di porta: .
        /// </summary>
        public static string OpenKnownPortNumber {
            get {
                return ResourceManager.GetString("OpenKnownPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Descrizione della regola (lasciare vuoto per utilizzare il nome del servizio): .
        /// </summary>
        public static string OpenKnownPortRuleDescription {
            get {
                return ResourceManager.GetString("OpenKnownPortRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata della regola (0 o lasciare vuoto per renderla permanente): .
        /// </summary>
        public static string OpenKnownPortRuleLifetime {
            get {
                return ResourceManager.GetString("OpenKnownPortRuleLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome della regola da inserire (LIST per elencarle): .
        /// </summary>
        public static string OpenKnownPortRuleName {
            get {
                return ResourceManager.GetString("OpenKnownPortRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Usare il numero di porta standard per la porta pubblica? (NB: la porta potrebbe essere bloccata dal tuo ISP) (y/n): .
        /// </summary>
        public static string OpenKnownPortUseStandardExternalPort {
            get {
                return ResourceManager.GetString("OpenKnownPortUseStandardExternalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Usare il numero di porta standard per la porta privata (y/n)?.
        /// </summary>
        public static string OpenKnownPortUseStandardInternalPort {
            get {
                return ResourceManager.GetString("OpenKnownPortUseStandardInternalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante la creazione della regola, codice di errore .
        /// </summary>
        public static string OpenPortError {
            get {
                return ResourceManager.GetString("OpenPortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo indicato non valido..
        /// </summary>
        public static string OpenPortFormatExceptionErrorText {
            get {
                return ResourceManager.GetString("OpenPortFormatExceptionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valore non valido, non può essere minore di 0..
        /// </summary>
        public static string OpenPortInvalidLifetime {
            get {
                return ResourceManager.GetString("OpenPortInvalidLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valore non valido, i valori possibili vanno da 1 a 65535..
        /// </summary>
        public static string OpenPortInvalidPort {
            get {
                return ResourceManager.GetString("OpenPortInvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo IP dispositivo (Local per questo computer): .
        /// </summary>
        public static string OpenPortIPAddress {
            get {
                return ResourceManager.GetString("OpenPortIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Validità (in secondi, 0 per infinito): .
        /// </summary>
        public static string OpenPortLifetime {
            get {
                return ResourceManager.GetString("OpenPortLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valore non valido..
        /// </summary>
        public static string OpenPortLifetimeNaN {
            get {
                return ResourceManager.GetString("OpenPortLifetimeNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apertura porta....
        /// </summary>
        public static string OpenPortOpening {
            get {
                return ResourceManager.GetString("OpenPortOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aperta porta .
        /// </summary>
        public static string OpenPortOpeningComplete1 {
            get {
                return ResourceManager.GetString("OpenPortOpeningComplete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  sul router..
        /// </summary>
        public static string OpenPortOpeningComplete2 {
            get {
                return ResourceManager.GetString("OpenPortOpeningComplete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Protocollo indicato non valido..
        /// </summary>
        public static string OpenPortProtocolInvalid {
            get {
                return ResourceManager.GetString("OpenPortProtocolInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Protocollo (TCP, UDP oppure Both): .
        /// </summary>
        public static string OpenPortProtocolSelection {
            get {
                return ResourceManager.GetString("OpenPortProtocolSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esistono sia una regolca TCP che una regola UDP per una delle porte indicate..
        /// </summary>
        public static string OpenPortRangeAlreadyExistsBothProtocols {
            get {
                return ResourceManager.GetString("OpenPortRangeAlreadyExistsBothProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Una regola TCP per una delle porte esiste già, saranno create soltanto le regole UDP..
        /// </summary>
        public static string OpenPortRangeAlreadyExistsTCP {
            get {
                return ResourceManager.GetString("OpenPortRangeAlreadyExistsTCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Una regola UDP per una delle porte esiste già saranno create soltanto le regole TCP..
        /// </summary>
        public static string OpenPortRangeAlreadyExistsUDP {
            get {
                return ResourceManager.GetString("OpenPortRangeAlreadyExistsUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Una delle porte esterne appartenenti al raggio è già aperta..
        /// </summary>
        public static string OpenPortRangeExternalAlreadyOpen {
            get {
                return ResourceManager.GetString("OpenPortRangeExternalAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Porta esterna finale: .
        /// </summary>
        public static string OpenPortRangeExternalEndingPort {
            get {
                return ResourceManager.GetString("OpenPortRangeExternalEndingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Porta esterna iniziale: .
        /// </summary>
        public static string OpenPortRangeExternalStartingPort {
            get {
                return ResourceManager.GetString("OpenPortRangeExternalStartingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Una delle porte interne appartenenti al raggio è già aperta..
        /// </summary>
        public static string OpenPortRangeInternalAlreadyOpen {
            get {
                return ResourceManager.GetString("OpenPortRangeInternalAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Porta interna finale: .
        /// </summary>
        public static string OpenPortRangeInternalEndingPort {
            get {
                return ResourceManager.GetString("OpenPortRangeInternalEndingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Porta interna iniziale: .
        /// </summary>
        public static string OpenPortRangeInternalStartingPort {
            get {
                return ResourceManager.GetString("OpenPortRangeInternalStartingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aperto raggio di porte da .
        /// </summary>
        public static string OpenPortRangeOpened1 {
            get {
                return ResourceManager.GetString("OpenPortRangeOpened1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  a .
        /// </summary>
        public static string OpenPortRangeOpened2 {
            get {
                return ResourceManager.GetString("OpenPortRangeOpened2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  sul router..
        /// </summary>
        public static string OpenPortRangeOpened3 {
            get {
                return ResourceManager.GetString("OpenPortRangeOpened3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apertura porte....
        /// </summary>
        public static string OpenPortRangeOpening {
            get {
                return ResourceManager.GetString("OpenPortRangeOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esiste già una regola con i dati forniti..
        /// </summary>
        public static string OpenPortRuleAlreadyExists {
            get {
                return ResourceManager.GetString("OpenPortRuleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esistono sia una regola TCP che una regola UDP con i dati forniti..
        /// </summary>
        public static string OpenPortRuleAlreadyExistsBothProtocols {
            get {
                return ResourceManager.GetString("OpenPortRuleAlreadyExistsBothProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Una regola TCP con i dati forniti esiste già, sarà creata soltanto una regola UDP..
        /// </summary>
        public static string OpenPortRuleAlreadyExistsTCP {
            get {
                return ResourceManager.GetString("OpenPortRuleAlreadyExistsTCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Una regola UDP con i dati forniti esiste già, sarà creata soltanto una regola TCP..
        /// </summary>
        public static string OpenPortRuleAlreadyExistsUDP {
            get {
                return ResourceManager.GetString("OpenPortRuleAlreadyExistsUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricerca di una regola già esistente con i dati forniti....
        /// </summary>
        public static string OpenPortRuleLookup {
            get {
                return ResourceManager.GetString("OpenPortRuleLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il percorso del file supera la massima lunghezza definita dal sistema..
        /// </summary>
        public static string PathTooLongExceptionText {
            get {
                return ResourceManager.GetString("PathTooLongExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo IP dispositivo: .
        /// </summary>
        public static string PortMappingAddress {
            get {
                return ResourceManager.GetString("PortMappingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Descrizione: .
        /// </summary>
        public static string PortMappingDescription {
            get {
                return ResourceManager.GetString("PortMappingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Porta esterna: .
        /// </summary>
        public static string PortMappingExternalPort {
            get {
                return ResourceManager.GetString("PortMappingExternalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Porta interna: .
        /// </summary>
        public static string PortMappingInternalPort {
            get {
                return ResourceManager.GetString("PortMappingInternalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Protocollo: .
        /// </summary>
        public static string PortMappingProtocol {
            get {
                return ResourceManager.GetString("PortMappingProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Queste sono le regole di port mapping attualmente impostate:.
        /// </summary>
        public static string PortMappingsListing {
            get {
                return ResourceManager.GetString("PortMappingsListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a NB: Vengono elencate soltanto le regole create tramite UPnP, le regole impostate manualmente non sono considerate..
        /// </summary>
        public static string PortMappingsListingWarning {
            get {
                return ResourceManager.GetString("PortMappingsListingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valida per .
        /// </summary>
        public static string PortMappingValidFor {
            get {
                return ResourceManager.GetString("PortMappingValidFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recupero regole attualmente impostate....
        /// </summary>
        public static string RuleSetRecovery {
            get {
                return ResourceManager.GetString("RuleSetRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Una o più operazioni nello script sono fallite..
        /// </summary>
        public static string ScriptFailed {
            get {
                return ResourceManager.GetString("ScriptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a L&apos;elaborazione degli script è disattivata, premere un tasto per chiudere l&apos;applicazione..
        /// </summary>
        public static string ScriptingDisabledWarning {
            get {
                return ResourceManager.GetString("ScriptingDisabledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scripting disabilitato..
        /// </summary>
        public static string ScriptingSettingDisabled {
            get {
                return ResourceManager.GetString("ScriptingSettingDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scripting abilitato..
        /// </summary>
        public static string ScriptingSettingEnabled {
            get {
                return ResourceManager.GetString("ScriptingSettingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esecuzione script....
        /// </summary>
        public static string ScriptRunning {
            get {
                return ResourceManager.GetString("ScriptRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Script completato senza errori..
        /// </summary>
        public static string ScriptSucceded {
            get {
                return ResourceManager.GetString("ScriptSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare il dispositivo su cui effettuare le operazioni: .
        /// </summary>
        public static string SelectDevice {
            get {
                return ResourceManager.GetString("SelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare l&apos;impostazione da modificare (0 per tornare indietro): .
        /// </summary>
        public static string SettingsEditSelection {
            get {
                return ResourceManager.GetString("SettingsEditSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni caricate..
        /// </summary>
        public static string SettingsLoaded {
            get {
                return ResourceManager.GetString("SettingsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caricamento impostazioni....
        /// </summary>
        public static string SettingsLoading {
            get {
                return ResourceManager.GetString("SettingsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1) Tempo di rilevamento dispositivi (in secondi): .
        /// </summary>
        public static string SettingsName1 {
            get {
                return ResourceManager.GetString("SettingsName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 2) Scegli il primo dispositivo trovato: .
        /// </summary>
        public static string SettingsName2 {
            get {
                return ResourceManager.GetString("SettingsName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 3) Scripting abilitato: .
        /// </summary>
        public static string SettingsName3 {
            get {
                return ResourceManager.GetString("SettingsName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No.
        /// </summary>
        public static string SettingsNo {
            get {
                return ResourceManager.GetString("SettingsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sì.
        /// </summary>
        public static string SettingsYes {
            get {
                return ResourceManager.GetString("SettingsYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Programma gestione mappatura porte NAT.
        /// </summary>
        public static string TitleString {
            get {
                return ResourceManager.GetString("TitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accesso negato: .
        /// </summary>
        public static string UnauthorizedAccessExceptionDetailedText {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionDetailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezione: .
        /// </summary>
        public static string UserSelection {
            get {
                return ResourceManager.GetString("UserSelection", resourceCulture);
            }
        }
    }
}
