//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatAutoMapperGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NatAutoMapperGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante il recupero dell&apos;indirizzo IP locale..
        /// </summary>
        internal static string LocalIPUnavailableMessage {
            get {
                return ResourceManager.GetString("LocalIPUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile recuperare l&apos;indirizzo locale.
        /// </summary>
        internal static string LocalIPUnavailableTitle {
            get {
                return ResourceManager.GetString("LocalIPUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Funzione non disponibile..
        /// </summary>
        internal static string NotImplementedMessage {
            get {
                return ResourceManager.GetString("NotImplementedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Funzione non implementata.
        /// </summary>
        internal static string NotImplementedTitle {
            get {
                return ResourceManager.GetString("NotImplementedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a L&apos;indirizzo fornito non è un un indirizzo locale..
        /// </summary>
        internal static string NotLocalIPErrorMessage {
            get {
                return ResourceManager.GetString("NotLocalIPErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo non valido.
        /// </summary>
        internal static string NotLocalIPErrorTitle {
            get {
                return ResourceManager.GetString("NotLocalIPErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile connettersi allo strumento di mappatura porte..
        /// </summary>
        internal static string NotSyncedErrorMessage {
            get {
                return ResourceManager.GetString("NotSyncedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile sincronizzare i processi.
        /// </summary>
        internal static string NotSyncedErrorTitle {
            get {
                return ResourceManager.GetString("NotSyncedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Raggio di porte non valido..
        /// </summary>
        internal static string PortRangeInvalidValuesErrorText {
            get {
                return ResourceManager.GetString("PortRangeInvalidValuesErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valori non validi..
        /// </summary>
        internal static string PortRangeInvalidValuesErrorTitle {
            get {
                return ResourceManager.GetString("PortRangeInvalidValuesErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare lo script da avviare.
        /// </summary>
        internal static string RunScriptFileDialogTitle {
            get {
                return ResourceManager.GetString("RunScriptFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Script NatAutoMapper|*.nat.
        /// </summary>
        internal static string RunScriptFilterText {
            get {
                return ResourceManager.GetString("RunScriptFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lo strumento di mappatura porte NAT è terminato in modo imprevisto, riavviare il programma?.
        /// </summary>
        internal static string ToolTerminatedErrorMessage {
            get {
                return ResourceManager.GetString("ToolTerminatedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Processo terminato.
        /// </summary>
        internal static string ToolTerminatedErrorTitle {
            get {
                return ResourceManager.GetString("ToolTerminatedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indefinito.
        /// </summary>
        internal static string UndefinedLifetime {
            get {
                return ResourceManager.GetString("UndefinedLifetime", resourceCulture);
            }
        }
    }
}
